parameters:

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASS)%"
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            IntelligibilityPortal:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/PortalBundle/Entity'
                prefix: 'Intelligibility\PortalBundle\Entity'
                alias: Intelligibility
            IntelligibilityAdmin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AdminBundle/Entity'
                prefix: 'Intelligibility\AdminBundle\Entity'
                alias: Intelligibility