twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig', 'custom_styles.html.twig']
    globals:
        localizator: '@Intelligibility\CoreBundle\Util\LocaleService'